version: '3.9'

services: 
  mongo:
    image: mongo:5.0-focal
    container_name: accounts-database
    environment:
      MONGO_INITDB_ROOT_USERNAME: dbroot
      MONGO_INITDB_ROOT_PASSWORD: dbroot
    command: mongod --port 16100
    ports:
      - "16100:16100"
    volumes:
      - accounts-database:/data/db

  service:
    container_name: accounts-service
    build:
      context: .
      dockerfile: Victa.Backend.Accounts/Dockerfile.develop
      args: 
        BUILD_CONFIGURATION: Debug
    depends_on: [mongo]
    environment:
      # db
      DB_NAME: Accounts
      DB_CONN: mongodb://dbroot:dbroot@mongo:16100
        
      ASPNETCORE_ENVIRONMENT: Development

      # GCP
      GCP_PROJECT_ID: victa-dev-366313
      GOOGLE_CLOUD_PROJECT: victa-dev-366313

      JAEGER_AGENT_HOST: jaeger
      JAEGER_AGENT_PORT: 6831
    ports:
      - "16000:80"

volumes:  
  accounts-database: