name: Deploy release (Pulumi)
on:
  release: 
    types: [published]

jobs:
  deploy_prod:
    name: Deploy release to production
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read 
    env:
      CI_STAGE: prod
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - id: auth
        name: Authenticate with Google 🔑
        uses: google-github-actions/auth@v0.4.2
        with:
          token_format: "access_token"
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS_PROD }}"
          export_default_credentials: true

      - uses: "docker/login-action@v1"
        with:
          registry: "gcr.io" # or REGION-docker.pkg.dev
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.access_token }}"

      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: victa/Victa.Backend.Accounts.Deployment/prod
          work-dir: ./Victa.Backend.Accounts.Deployment
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
