name: Deploy develop (Pulumi)
on:
  push: 
    branches:
      - 'develop'

jobs:
  update:
    name: Deploy to dev
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read 
    env:
      CI_STAGE: dev
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - id: auth
        name: Authenticate with Google 🔑
        uses: google-github-actions/auth@v0.4.2
        with:
          token_format: "access_token"
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS_DEV }}"

      - uses: "docker/login-action@v1"
        with:
          registry: "gcr.io"  
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.access_token }}"

      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: victa/Victa.Backend.Accounts.Deployment/dev
          work-dir: ./Victa.Backend.Accounts.Deployment
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
